version: '3'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - ADGUARDHOME_LISTENINGPORT=53
      - ADGUARDHOME_PORT=3000

  sniproxy:
    container_name: sniproxy
    build: ./sniproxy
    image: sniproxy
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./sniproxy/sniproxy.conf:/etc/sniproxy/sniproxy.conf
      - ./sniproxy/logs:/var/log/sniproxy
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai